FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY packages/shared-types/package*.json ./packages/shared-types/
COPY apps/api/package*.json ./apps/api/

RUN npm install

COPY packages/shared-types ./packages/shared-types
COPY apps/api ./apps/api

RUN npm --workspace=packages/shared-types run build
RUN npm --workspace=apps/api run build

EXPOSE 3001

CMD ["npm", "--workspace=apps/api", "start"]
