FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY packages/shared-types/package*.json ./packages/shared-types/
COPY apps/web/package*.json ./apps/web/

RUN npm install

COPY packages/shared-types ./packages/shared-types
COPY apps/web ./apps/web

RUN npm --workspace=packages/shared-types run build
RUN npm --workspace=apps/web run build

EXPOSE 3000

CMD ["npm", "--workspace=apps/web", "start"]
